CREATE TABLE IF NOT EXISTS users(
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    name VARCHAR(255) NOT NULL,
                                    email VARCHAR(255) NOT NULL,
                                    CONSTRAINT pk_user PRIMARY KEY (id),
                                    CONSTRAINT UQ_USER UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items(
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    user_id BIGINT NOT NULL,
                                    name VARCHAR(255) NOT NULL,
                                    description VARCHAR(2000) NOT NULL,
                                    available BOOLEAN NOT NULL,
                                    CONSTRAINT pk_item PRIMARY KEY (id),
                                    CONSTRAINT fk_item_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        item_id BIGINT NOT NULL REFERENCES items (id) ON DELETE CASCADE,
                                        booker_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                                        status VARCHAR(20) NOT NULL,
                                        start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        end_time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);


CREATE TABLE IF NOT EXISTS comments (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                        text VARCHAR(2000) NOT NULL,
                                        item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
                                        author_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
                                        created TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS item_requests(
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            description VARCHAR(2000) NOT NULL,
                                            requestor_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                                            created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

ALTER TABLE items
    ADD COLUMN IF NOT EXISTS request_id BIGINT REFERENCES item_requests(id) ON DELETE SET NULL;